name       : libnitrokey
version    : 3.4.1
release    : 1
source     :
    - https://github.com/Nitrokey/libnitrokey/releases/download/v3.4.1/libnitrokey-v3.4.1.tar.gz : 98d519238809472dfd687b9f9daeaf7be624a77c0ab840a2d8effa049bcac31e
license    : LGPL-3.0-or-later
component  : security.library
summary    : Communicate with Nitrokey stick devices in a clean and easy manner. 
description: |
    Libnitrokey is a project to communicate with Nitrokey Pro and Storage devices in a clean and easy manner.
builddeps  :
    - pkgconfig(hidapi-libusb)
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install